// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWVggxfgoTdVE5hlsHngR8Ctq1-ajo4RU',
    appId: '1:108090409948:web:8493dc1f84026cab9c8519',
    messagingSenderId: '108090409948',
    projectId: 'chatapp-1e3ea',
    authDomain: 'chatapp-1e3ea.firebaseapp.com',
    storageBucket: 'chatapp-1e3ea.appspot.com',
    measurementId: 'G-YD4CPBRQG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA34vxSd_Jjh79vlvkwMbXpzIwe2xW2NIQ',
    appId: '1:108090409948:android:59e76f5a0ff43f7e9c8519',
    messagingSenderId: '108090409948',
    projectId: 'chatapp-1e3ea',
    storageBucket: 'chatapp-1e3ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhV6VyAWBM78K-HLfb69y2yq2bCSSEnZ0',
    appId: '1:108090409948:ios:da47399911ccde669c8519',
    messagingSenderId: '108090409948',
    projectId: 'chatapp-1e3ea',
    storageBucket: 'chatapp-1e3ea.appspot.com',
    iosClientId: '108090409948-s5gjh2vf7qbp8gmetcfcp6uhv3da7v67.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhV6VyAWBM78K-HLfb69y2yq2bCSSEnZ0',
    appId: '1:108090409948:ios:da47399911ccde669c8519',
    messagingSenderId: '108090409948',
    projectId: 'chatapp-1e3ea',
    storageBucket: 'chatapp-1e3ea.appspot.com',
    iosClientId: '108090409948-s5gjh2vf7qbp8gmetcfcp6uhv3da7v67.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
